/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('@dpzvc3/vue/es/badge')['default']
    Cell: typeof import('@dpzvc3/vue/es/cell')['default']
    CellSwipe: typeof import('@dpzvc3/vue/es/cell-swipe')['default']
    CheckBox: typeof import('@dpzvc3/vue/es/check-box')['default']
    DpButton: typeof import('@dpzvc3/vue/es/dp-button')['default']
    DpHeader: typeof import('@dpzvc3/vue/es/dp-header')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadMore: typeof import('@dpzvc3/vue/es/load-more')['default']
    RadioBox: typeof import('@dpzvc3/vue/es/radio-box')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToTop: typeof import('@dpzvc3/vue/es/to-top')['default']
    Upload: typeof import('@dpzvc3/vue/es/upload')['default']
  }
}
