/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionSheet: typeof import('@dpzvc3/vue/es/action-sheet')['default']
    Badge: typeof import('@dpzvc3/vue/es/badge')['default']
    Card: typeof import('@dpzvc3/vue/es/card')['default']
    Cell: typeof import('@dpzvc3/vue/es/cell')['default']
    CellSwipe: typeof import('@dpzvc3/vue/es/cell-swipe')['default']
    DpButton: typeof import('@dpzvc3/vue/es/dp-button')['default']
    DpHeader: typeof import('@dpzvc3/vue/es/dp-header')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadMore: typeof import('@dpzvc3/vue/es/load-more')['default']
    Picker: typeof import('@dpzvc3/vue/es/picker')['default']
    Popup: typeof import('@dpzvc3/vue/es/popup')['default']
    Rater: typeof import('@dpzvc3/vue/es/rater')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideBar: typeof import('@dpzvc3/vue/es/slide-bar')['default']
    Spinner: typeof import('@dpzvc3/vue/es/spinner')['default']
    Swipe: typeof import('@dpzvc3/vue/es/swipe')['default']
    SwitchBar: typeof import('@dpzvc3/vue/es/switch-bar')['default']
    Tab: typeof import('@dpzvc3/vue/es/tab')['default']
    TextBar: typeof import('@dpzvc3/vue/es/text-bar')['default']
    ToTop: typeof import('@dpzvc3/vue/es/to-top')['default']
    Upload: typeof import('@dpzvc3/vue/es/upload')['default']
  }
}
