/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cell: typeof import('@dpzvc3/vue/es/cell')['default']
    CheckBox: typeof import('@dpzvc3/vue/es/check-box')['CheckBox']
    CheckBoxGroup: typeof import('@dpzvc3/vue/es/check-box')['CheckBoxGroup']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RadioBox: typeof import('@dpzvc3/vue/es/radio-box')['RadioBox']
    RadioBoxGroup: typeof import('@dpzvc3/vue/es/radio-box')['RadioBoxGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
